name: use_validate
description: A small library for validating input fields.
version: 1.0.4
repository: https://github.com/farajshuaib/use_validate
homepage: https://github.com/farajshuaib/use_validate


environment:
  sdk: ^3.0.5

dependencies:
dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
